name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  xml: ^6.0.1
  image: ^4.0.17
  collection: ^1.15.0
  logger: ^1.3.0
  flutter_image_compress: ^2.3.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  test: ^1.16.7
  path: ^1.8.1
  pedantic: ^1.11.0
